### ISSUE TITLE
Where do I put my API Key and Filename and Path?

### ISSUE THREAD

**Issue by ghost** [Zaargh/ocr.space_code_example#2]
Where do I put my API Key and Filename and Path?

**Comment by Zaargh** [comment]
I see it may not be obvious, as this project is quite old and I didn't know good Python practices back then.

You should pass API key and filename with path as arguments to `ocr_space_file` function, as described in the docstring [here](https://github.com/Zaargh/ocr.space_code_example/blob/124155fbb8d215889974b6d7cfd65584e56df954/ocrspace_example.py#L10).

Example:

```python
result = ocr_space_file("/home/zaargh/Pictures/my_picture_with_text.png", api_key="MY_API_KEY")
```

**Comment by Zaargh** [comment]
I don't intend on changing this anytime soon, as I no longer use `ocr.space` myself. Hence closing the issue.
