### ISSUE TITLE
Running Code but its not returning anything. 

### ISSUE THREAD

**Issue by ghost** [Zaargh/ocr.space_code_example#3]
Running Code but its not returning anything. I am using an .png image. The image works if I manually go to the website and use it. The python scripts runs successfully with no errors but doesn't return the text of the image?

**Comment by Zaargh** [comment]
Please provide a little bit more info, or a code example. It worked for me just now (with `helloworld` API key):

```
In [2]: ocr_space_file('test.png')
Out[2]: '{"ParsedResults":[{"TextOverlay":{"Lines":[],"HasOverlay":false,"Message":"Text overlay is not provided as it is not requested"},"FileParseExitCode":1,"ParsedText":"Help people interested in this repository understand your project by adding a README. \\r\\nAdd a README \\r\\n","ErrorMessage":"","ErrorDetails":""}],"OCRExitCode":1,"IsErroredOnProcessing":false,"ErrorMessage":null,"ErrorDetails":null,"ProcessingTimeInMilliseconds":"3683","SearchablePDFURL":"Searchable PDF not generated as it was not requested."}'
```

`test.png`:
![test](https://user-images.githubusercontent.com/12481784/40473718-3f0fcb64-5f3d-11e8-8dbd-f2b7e290b17a.png)
